# L5 Data Cleaning & EDA

- Structure
  
  - File Formats (csv, tsv, json)

  - Variable Types

- Granularity & Temporality

- Faithfulness

  - Missing Values

<div style="background-color:#3b82f630; padding:12px 16px; border-left:5px solid #3b82f6; width:100%; max-width:100%; box-sizing:border-box; overflow-x:auto;">

<strong>Definition:</strong> **Data Cleaning 数据清洗 / Data Wrangling 数据整理**

- The process of transforming raw data to facilitate subsequent analysis

	- May address issues like:
  
    	- Unclear structure & formatting

		- Missing & corrupted values
		
		- Unit conversions, etc.

- 简而言之就是做菜前要“备菜”

</div>

<div style="background-color:#3b82f630; padding:12px 16px; border-left:5px solid #3b82f6; width:100%; max-width:100%; box-sizing:border-box; overflow-x:auto;">

<strong>Definition:</strong> **Exploratory Data Analysis (EDA) 数据探索**

- The process of understanding a new dataset

- 就是扫一眼数据长啥样，关于啥的，算算简单的平均数，方差啥的统计指标有个简单的初步理解，看看有没有什么有意思的特征或问题可以进一步探索

</div>

- Just some fancy words

## 1 Structure

- We usually prefer **rectangular data** for data analysis (i.e. A tablelike structure of data **with rows and cols**)

	- Easy to manipulate & analyze

- A key goal of data cleaning is to **make initial data more rectangular**

There are 2 types of rectangular data

- **Tables (表)**: have named columns with **different data types** and are manipulated using data transformation languages

- **Matrices (矩阵)**: contain **numeric data** of the **same type** and are manipulated using linear algebra

<div style="background-color:#eab30826; padding:12px 16px; border-left:5px solid #eab308; width:100%; max-width:100%; box-sizing:border-box; overflow-x:auto;">

<strong>Key idea:</strong> 

- Whether it contains different types of data is the key difference

- Matrices can be viewed as pure-number tables, which is a simple version of table

</div>

### File Formats

- There are many file types for storing structured data: TSV, JSON, XML, ASCII, SAS, etc

- We just introduce CSV, TSV, and JSON in lecture, you can learn others by yourself when encountering them

In [9]:
import pandas as pd
import numpy as np

**CSV (Comma-Separated Values)**

- Let's see the raw data before it is loaded into a df

- We can use `repr()` func to return raw string

In [1]:
with open("elections.csv", "r") as table:
    i = 0
    for row in table:
        print(repr(row))
        i += 1
        if i > 3:
            break

'Year,Candidate,Party,Popular vote,Result,%\n'
'1824,Andrew Jackson,Democratic-Republican,151271,loss,57.21012204\n'
'1824,John Quincy Adams,Democratic-Republican,113142,win,42.78987796\n'
'1828,Andrew Jackson,Democratic,642806,win,56.20392707\n'

- Each line is a **string**

- Each row (record) is delimited by a newline `\n`

- Each col (field) is delimited by a comma `,` (hence **comma-separated** values, csv)

In [10]:
pd.read_csv("elections.csv").head(5)

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789

**TSV (Tab-Separated Values)**

- Same logic as for csv
  
- The record (row) is delimited by `\n`

- The field (col) is delimited by tab character `\t`

In [5]:
with open("elections.txt", "r") as table:
    i = 0
    for row in table:
        print(repr(row))
        i += 1
        if i > 3:
            break

'\ufeffYear\tCandidate\tParty\tPopular vote\tResult\t%\n'
'1824\tAndrew Jackson\tDemocratic-Republican\t151271\tloss\t57.21012204\n'
'1824\tJohn Quincy Adams\tDemocratic-Republican\t113142\twin\t42.78987796\n'
'1828\tAndrew Jackson\tDemocratic\t642806\twin\t56.20392707\n'

In [12]:
# We can also use the read_csv function to read tsv
# But we need to specify the delimiter as string '\t'
pd.read_csv("elections.txt", sep='\t').head(3)

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927

<div style="background-color:#8b5cf630; padding:12px 16px; border-left:5px solid #8b5cf6; width:100%; max-width:100%; box-sizing:border-box; overflow-x:auto;">

<strong>Question:</strong> **How does `pandas` differentiate a delimiter `,` and a actual text `,` like in `8,900`?**

- It uses [quotechar parameter](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) to solve this

**quotechar: *str (length 1), optional***

Character used to denote the start and end of a quoted item.

Quoted items can include the delimiter and it will be ignored.

Only **one character** (length 1) is allowed

**e.g.**

`quotechar='"'`

- It means `"` is the sign of the start & end

```
"London, UK"
↑          ↑
start      end
```
</div>

**JSON (JavaScript Object Notation)**

- It is similar to a Python dictionary

In [13]:
with open("elections.json", "r") as table:
    i = 0
    for row in table:
        print(row)
        i += 1
        if i > 8:
            break

[

 {

   "Year": 1824,

   "Candidate": "Andrew Jackson",

   "Party": "Democratic-Republican",

   "Popular vote": 151271,

   "Result": "loss",

   "%": 57.21012204

 },

In [15]:
pd.read_json('elections.json').head(3)

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927

### Variable Types